/*
 * File: app/view/CarListings.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CarListings.view.CarListings', {
    extend: 'Ext.panel.Panel',

    frame: true,
    autoScroll: true,
    layout: {
        align: 'stretch',
        pack: 'center',
        type: 'hbox'
    },
    title: 'Cleaning Viewer',
    titleAlign: 'center',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    title: 'Old Pubs/Trec',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            html: 'HELLO BRYAN!',
                            title: 'Pub'
                        },
                        {
                            xtype: 'panel',
                            html: 'I\'M HERE!',
                            title: 'Trec'
                        }
                    ]
                },
                {
                    xtype: 'tabpanel',
                    flex: 1,
                    title: 'New Pubs/Trec',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            html: 'WHATS UP!',
                            title: 'Pub'
                        },
                        {
                            xtype: 'panel',
                            html: 'YO!',
                            title: 'Trec'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});